---

- name: vault | extract binary
  become: true
  unarchive:
    src: "{{ os_dir_temp }}/{{ package_name_vault }}.zip"
    dest: "{{ os_dir_packages }}/vault/{{ vault_version }}"
    owner: vault
    group: vault
    remote_src: yes

- name: vault | symlink binary
  become: true
  notify:
  - restart_unit_vault
  file:
    src: "{{ os_dir_packages }}/vault/{{ vault_version }}/vault"
    dest: "{{ os_dir_binaries }}/vault"
    owner: vault
    group: vault
    state: link
