---
# tasks file for roles/nomad

- name: only run if os is supported
  block:

  - include_vars: coreos.yml
    when: ansible_service_mgr == "systemd"
    #when: ansible_os_family == "Container Linux by CoreOS"

  - include: vault-download.yml
    tags: download

  - include: vault-install.yml
    tags: install

  - block:
    tags: configure

    - include: vault-cfg_user.yml
      tags: optional

    - include: vault-cfg_systemd.yml
      tags: optional

    when: vault['server']

  when: ansible_service_mgr == "systemd"
  #when: ansible_os_family == "Container Linux by CoreOS"
