---

- include: _assert.yml

- include_vars: coreos.yml

- include: _download.yml
- include: _user.yml
- include: _folders.yml
- include: _install.yml
- include: _configure.yml
- include: _initialize.yml
