#
# Configures the Vault server
#
---

- name: vault | create service folders
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "bin_name['vault']"
    group: "bin_name['vault']"
    mode: 0755
  loop:
  - "{{ base_dir['logs'] }}/{{ bin_name['vault'] }}"
  - "{{ base_dir['data'] }}/{{ bin_name['vault'] }}"

- name: vault | generate service configurationfile
  become: true
  notify:
  - reload_systemd_daemon
  - restart_unit_vault
  template:
    dest: "{{ base_dir['configs'] }}/{{ bin_name['vault'] }}.d/{{ item }}"
    src: "{{ bin_name['vault'] }}/{{ item }}.j2"
    owner: "{{ bin_name['vault'] }}"
    group: "{{ bin_name['vault'] }}"
    mode: 0640
  loop:
  - 50-vault.hcl

- name: vault | create systemd unit
  become: true
  notify:
  - reload_systemd_daemon
  - restart_unit_vault
  template:
    dest: "{{ base_dir['systemd'] }}/{{ item }}"
    src: "{{ bin_name['vault'] }}/systemd/{{ item }}.j2"
    owner: root
    group: root
    mode: 0644
  loop:
  - vault.service

- name: vault | start and enable unit
  become: true
  notify:
  - reload_systemd_daemon
  systemd:
    name: vault
    state: started
    enabled: yes
    masked: no
